server:
  port: 8082




spring:
  application:
    name: api-produto
  datasource:
    url: jdbc:postgresql://db-produtos:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/